### ISSUE TITLE
Future support for having PHP code inside page content

### ISSUE THREAD

**Issue by VaasKahnGrim** [licensecart/BlestaCMS#5]
Basically it would be quite useful to have the CMS able to have php code along side static html for pages. Would be quite useful for pages that might need to have functionality to it. For example having a news feed page that pulls news posts stored in mysql or a live twitter feed or perhaps even a built in service status page made with the CMS. Getting php support for the CMS could allow for ALOT of useful possibilities

**Comment by atlanical** [comment]
Hi there, 

Sorry it won't be possible for the BlestaCMS, we were looking in a way to do it in the past but hit a wall. You can use another third-party cms: https://www.blesta.com/forums/index.php?/topic/10676-cms-pro-announcements/

We will be looking into it in the future but won't be part of the Community Edition. 

Kind regards,
Mike
