### ISSUE TITLE
Blesta CMS plugin does not appear in 'Available' list

### ISSUE THREAD

**Issue by pixelpaulaus** [licensecart/BlestaCMS#6]
installed, cleared cache and nothing shows.
I installed just as instructed, but nothing is shown in the list.
I have tried on 2 new installs of blesta, and nothing shows.

**Comment by pixelpaulaus** [comment]
i commented out the line: 
`list($this->plugin) = $this->PluginManager->getByDir('blesta_cms');`
and it now lists.
But when you click install you get the error: 

SQLSTATE[23000]: Integrity constraint violation: 1048 Column 'uri' cannot be null

**Comment by atlanical** [comment]
Hi do you have discord? Because that is checking if the folder exists.

**Comment by atlanical** [comment]
I just realised this was fixed a while back.
