### ISSUE TITLE
Error 500, think Blesta_cms needs an update for Blesta 5.7

### ISSUE THREAD

**Issue by emar** [licensecart/BlestaCMS#8]
Hi,

I had an error 500 after upgrading to Blesta 5.7
So I decided to start disabling plugins to check for issues.
Renamed blesta_cms and Blesta front-end is working again.

**Comment by SwGraf** [comment]
This is the community edition. So we only merge changes/PR's sent in by the blesta community.

If you want a "maintaned" and more comprehensive CMS Plugin, then you can buy the CMS Pro from blesta.store

Kind regards
